//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompareTheGame.dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CompareTheGameEntities : DbContext
    {
        public CompareTheGameEntities()
            : base("name=CompareTheGameEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<GameGenre> GameGenres { get; set; }
        public virtual DbSet<GameMode> GameModes { get; set; }
        public virtual DbSet<GamePerspective> GamePerspectives { get; set; }
        public virtual DbSet<GamePlatform> GamePlatforms { get; set; }
        public virtual DbSet<GameScreenshot> GameScreenshots { get; set; }
        public virtual DbSet<GameTheme> GameThemes { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<Mode> Modes { get; set; }
        public virtual DbSet<Perspective> Perspectives { get; set; }
        public virtual DbSet<Platform> Platforms { get; set; }
        public virtual DbSet<Screenshot> Screenshots { get; set; }
        public virtual DbSet<Theme> Themes { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<VendorGameHistory> VendorGameHistories { get; set; }
        public virtual DbSet<VendorGameSetting> VendorGameSettings { get; set; }
    }
}
