//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompareTheGame.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.GameGenres = new HashSet<GameGenre>();
            this.GameModes = new HashSet<GameMode>();
            this.GamePerspectives = new HashSet<GamePerspective>();
            this.GamePlatforms = new HashSet<GamePlatform>();
            this.GameScreenshots = new HashSet<GameScreenshot>();
            this.GameThemes = new HashSet<GameTheme>();
            this.VendorGameHistories = new HashSet<VendorGameHistory>();
            this.VendorGameSettings = new HashSet<VendorGameSetting>();
        }
    
        public int GameID { get; set; }
        public int IGDBID { get; set; }
        public string GameName { get; set; }
        public string URL { get; set; }
        public string CoverImageURL { get; set; }
        public string StoreLine { get; set; }
        public string Summary { get; set; }
        public System.DateTime FirstReleaseDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<bool> Published { get; set; }
        public Nullable<System.DateTime> PublishModifiedDate { get; set; }
        public string PublishModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameGenre> GameGenres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameMode> GameModes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GamePerspective> GamePerspectives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GamePlatform> GamePlatforms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameScreenshot> GameScreenshots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameTheme> GameThemes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorGameHistory> VendorGameHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorGameSetting> VendorGameSettings { get; set; }
    }
}
