//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompareTheGame.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorGameSetting
    {
        public int VendorGameSettingsID { get; set; }
        public Nullable<int> PlatformID { get; set; }
        public Nullable<int> GameID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<bool> Automated { get; set; }
        public string XcodePrice { get; set; }
        public string XcodeSalePrice { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Platform Platform { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
