//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompareTheGame.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorGameHistory
    {
        public int VendorGameHistoryID { get; set; }
        public Nullable<int> GamePlatformID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public string Price { get; set; }
        public string SalePrice { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string PageURL { get; set; }
    
        public virtual GamePlatform GamePlatform { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
